# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Digital_Exp/MCU_v1/BOARD_TOP/BOARD_TOP.srcs/sources_1/ip/test_ROM/test_ROM.xci
# IP: The module: 'test_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Digital_Exp/MCU_v1/BOARD_TOP/BOARD_TOP.gen/sources_1/ip/test_ROM/test_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_ROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/Digital_Exp/MCU_v1/BOARD_TOP/BOARD_TOP.srcs/sources_1/ip/test_ROM/test_ROM.xci
# IP: The module: 'test_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Digital_Exp/MCU_v1/BOARD_TOP/BOARD_TOP.gen/sources_1/ip/test_ROM/test_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'test_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
